#!/bin/bash
# 
#  curl commands
#

set -e

printf "\n⏳   Loading order subscriptions \n"

curl -X POST 'http://orion:1026/v2/subscriptions/' \
	-H 'Content-Type: application/json' \
	-H 'fiware-service: openiot' \
	-H 'fiware-servicepath: /' \
	--data-raw '{
		"description": "Notify QuantumLeap of all Motion Sensor count changes",
		"subject": {"entities": [{"idPattern": "Order.*"}]},
		"notification": {
			"http": {"url": "http://quantumleap:8668/v2/notify"},
			"attrs": ["refPart","shopOrder","orderStatus","currentOperation","planedHours","actualHours","scheduledStart","scheduledEnd","actualStart","actualEnd","progress","scheduledDelay","progressDelay","actualStart","actualEnd"]
		}
	}'

curl -X POST 'http://orion:1026/v2/subscriptions/' \
	-H 'Content-Type: application/json' \
	-H 'fiware-service: openiot' \
	-H 'fiware-servicepath: /' \
	--data-raw '{
		"description": "Notify QuantumLeap of all Motion Sensor count changes",
		"subject": {"entities": [{"idPattern": "Part.*"}]},
		"notification": {
			"http": {"url": "http://quantumleap:8668/v2/notify"},
			"attrs": ["partNumber","serialNumber","partRev","cemb","planedHours","description"]
		}
	}'

curl -X POST 'http://orion:1026/v2/subscriptions/' \
	-H 'Content-Type: application/json' \
	-H 'fiware-service: openiot' \
	-H 'fiware-servicepath: /' \
	--data-raw '{
		"description": "Notify QuantumLeap of all Motion Sensor count changes",
		"subject": {"entities": [{"idPattern": "WorkCenter.*"}]},
		"notification": {
			"http": {"url": "http://quantumleap:8668/v2/notify"}
			"attrs": ["name","description"]
		}
	}'

curl -X POST 'http://orion:1026/v2/subscriptions/' \
	-H 'Content-Type: application/json' \
	-H 'fiware-service: openiot' \
	-H 'fiware-servicepath: /' \
	--data-raw '{
		"description": "Notify QuantumLeap of all Motion Sensor count changes",
		"subject": {"entities": [{"idPattern": "Operation.*"}]},
		"notification": {
				"http": {"url": "http://quantumleap:8668/v2/notify"},
				"attrs": ["workCenter_id","order_id","operationNumber","planedHours","operationStatus","fristRunDate","completeRunDate","setUpMan","manPowerHours","setUpMachine","machineHours","description"]
	  }
	}'
